### PR TITLE
Yarn docs update and index.html(VERSION 1.0.1)

### PR DESCRIPTION
**Pull request by KingLyrics**
Corrections have been made to the `index.HTML` page. Let me know if more corrections are needed before we proceed forward. Also the significant reduction in code. Version 1.0.0 had over 121 lines of code, whereas the version 1.0.1 has 112. @gmagnenat thank you for your contributions to the change in the code.

### CODE REVIEW

**Review by gmagnenat — APPROVED** [review]
I think that's good. We can of course refactor later when needed.

**Comment by gmagnenat** [comment]
I see there are conflicting files.. try to solve the issue or I'll look into it tonight. I'm out for the day.

**Comment by KingLyrics** [comment]
Thank you :)

**Comment by KingLyrics** [comment]
@gmagnenat I will try to resolve them now

**Pull request merged**
